query RunInput {
  cart {
    lines {
      quantity
      cost {
        totalAmount {
          amount
          currencyCode
        }
        amountPerQuantity {
          amount
          currencyCode
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            title
          }
        }
      }
    }
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
      totalAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      customer {
        id
      }
    }
    # Individual cart attributes for revlyft IDs
    userIpAttribute: attribute(key: "causal_funnel_user_ip") {
      value
    }
    hashValueAttribute: attribute(key: "causal_funnel_hash_value") {
      value
    }
    testTargetingAttribute: attribute(
      key: "causal_funnel_tests_targeting_data"
    ) {
      value
    }
  }
  discountNode {
    metafield(
      namespace: "$app:product-discount"
      key: "function-configuration"
    ) {
      value
    }
  }
}
