query RunInput {
  cart {
    lines {
      quantity
      cost {
        totalAmount {
          amount
          currencyCode
        }
        amountPerQuantity {
          amount
          currencyCode
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            title
          }
        }
      }
    }
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
      totalAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      customer {
        id
      }
    }
    # Individual cart attributes for A/B Test IDs
    deviceIdAttribute: attribute(key: "abtest_device_id") {
      value
    }
    hashValueAttribute: attribute(key: "abtest_hash_value") {
      value
    }
    testDataAttribute: attribute(key: "abtest_test_data") {
      value
    }
  }
  discountNode {
    metafield(
      namespace: "$app:product-discount"
      key: "function-configuration"
    ) {
      value
    }
  }
}
