
name = "revlyft-ab-testing"
uid = "52b10e53-1832-a831-eae3-b3b5c68830ba1da91eba"
type = "theme"

[settings]
icon = "logo.png"

[[settings.blocks]]
type = "revlyft_scripts"
name = "Revlyft Scripts"
target = "head"


# NEW: Add progress bar block
[[settings.blocks]]
type = "discount_progress_bar"
name = "Discount Progress Bar"
target = "section"

# Cart Drawer App Embed
[[settings.blocks]]
type = "revlyft-cart-drawer"
name = "Revlyft Cart Drawer"
target = "body"

