# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b633b97839927c8b34e5028c47d2c881"
application_url = "https://tracks-affiliate-ours-deals.trycloudflare.com"
embedded = true
name = "abtest"
handle = "abtest-6"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_script_tags,write_discounts,write_products,write_script_tags,write_files,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://tracks-affiliate-ours-deals.trycloudflare.com/auth/callback",
  "https://tracks-affiliate-ours-deals.trycloudflare.com/auth/shopify/callback",
  "https://tracks-affiliate-ours-deals.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
