# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e59db4a060f6e83ace4a512a5e178392"
application_url = "https://zero-ryan-asus-strength.trycloudflare.com"
embedded = true
name = "a-b-test-dev"
handle = "a-b-test-dev"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_script_tags,write_discounts,write_files,write_inventory,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://zero-ryan-asus-strength.trycloudflare.com/auth/callback",
  "https://zero-ryan-asus-strength.trycloudflare.com/auth/shopify/callback",
  "https://zero-ryan-asus-strength.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
