api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "product-discount"
uid = "d0f68f29-1841-f67e-43fd-d817ad592eda03aa57c0"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
