query CartInput {
  cart {
    lines {
      id
      quantity
      merchandise {
        ... on ProductVariant {
          id
          title
        }
      }
      cost {
        subtotalAmount {
          amount
        }
      }
    }
    # Individual cart attributes for revlyft IDs
    userIpAttribute: attribute(key: "causal_funnel_user_ip") {
      value
    }
    hashValueAttribute: attribute(key: "causal_funnel_hash_value") {
      value
    }
    testTargetingAttribute: attribute(
      key: "causal_funnel_tests_targeting_data"
    ) {
      value
    }
    testTimerAttribute: attribute(key: "causal_funnel_tests_start_time_data") {
      value
    }
    # Current time from frontend
    currentTimeAttribute: attribute(key: "causal_funnel_current_time") {
      value
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app:cart-discount", key: "function-configuration") {
      value
    }
  }
}
